CREATE TABLE Users
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(30) NOT NULL,
    surname varchar(50) NOT NULL,
    email varchar(75) NOT NULL UNIQUE,
    username varchar(30) NOT NULL UNIQUE,
    password varchar NOT NULL
);